# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###
POST http://127.0.0.1:8000/contact
Content-Type: application/json

{
  "name": "Lia",
  "email": "liad0541@gmail.com",
  "message": "hola miamor"
}
